---
- name: Create vm
  hosts: proxmox_1
  collections:
    - jocoutu.bashtop
  roles:
    - { role: proxmox, cmd: create, dest: 165, ram: 16000, core: 4, cpu: host }
    - { role: proxmox, cmd: create, dest: 111 }

- name: Async install k3s
  hosts: k3s_1
  collections:
    - jocoutu.bashtop
  roles:
    - { role: k3s, cmd: install }

- name: Install dns server
  hosts: dnsmasq_1
  collections:
    - jocoutu.bashtop
  roles:
    - { role: docker, cmd: install }
    - { role: dnsmasq, cmd: install }

- name: Create k3s apk
  hosts: k3s_1
  collections:
    - jocoutu.bashtop
  roles:
    - { role: awx, cmd: install }
    - { role: gitea, cmd: install }

- name: Install remote cli on localhost
  hosts: proxmox_1
  collections:
    - jocoutu.bashtop
  roles:
    - { role: awx, cmd: cli }
